insert into autor (cod_autor, nacionalidade_autor, nome_autor) values
(1, "IT", "Francesca Tomaz"),
(2, "BR", "Lucas Henrique"),
(3, "BR", "Pedro Lucas"),
(4, "BE", "Liah Olívia"),
(5, "BR", "Larissa Rodriguez"),
(6, "BR", ""),
(7, "CA", "Emma Stone"),
(8, "BR", "Lucas Henrique"),
(9, "US", "John Locke"),
(10, "BR", "Laura Siqueira"),
(11, "AU", "Liam Alexander"),
(12, "GR", "Nikko Oliver"),
(13, "BR", "Nicoli Tomaz "),
(14, "BR", "Lucas Henrique"),
(15, "AR", "Mattheo Borges"),
(16, "DK", "Eryk William"),
(17, "BR", "Olivia Silva"),
(18, "US", "Jason Tatum"),
(19, "FR", "Evan Fornier "),
(20, "GB", "Lewis Hamilton"),
